// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: validation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValidationClient is the client API for Validation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationClient interface {
	ValidateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type validationClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationClient(cc grpc.ClientConnInterface) ValidationClient {
	return &validationClient{cc}
}

func (c *validationClient) ValidateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, "/Validation/ValidateCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationServer is the server API for Validation service.
// All implementations must embed UnimplementedValidationServer
// for forward compatibility
type ValidationServer interface {
	ValidateCard(context.Context, *CardRequest) (*ValidationResponse, error)
	mustEmbedUnimplementedValidationServer()
}

// UnimplementedValidationServer must be embedded to have forward compatible implementations.
type UnimplementedValidationServer struct {
}

func (UnimplementedValidationServer) ValidateCard(context.Context, *CardRequest) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCard not implemented")
}
func (UnimplementedValidationServer) mustEmbedUnimplementedValidationServer() {}

// UnsafeValidationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationServer will
// result in compilation errors.
type UnsafeValidationServer interface {
	mustEmbedUnimplementedValidationServer()
}

func RegisterValidationServer(s grpc.ServiceRegistrar, srv ValidationServer) {
	s.RegisterService(&Validation_ServiceDesc, srv)
}

func _Validation_ValidateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServer).ValidateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validation/ValidateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServer).ValidateCard(ctx, req.(*CardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Validation_ServiceDesc is the grpc.ServiceDesc for Validation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Validation",
	HandlerType: (*ValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateCard",
			Handler:    _Validation_ValidateCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validation.proto",
}
